[goldmark.renderer]
  hardWraps = false
  unsafe = false # change to true to enable inclusion of rawHTML and math functions
  xhtml = false
[highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = false
  noClasses = false
  tabWidth = 2